# Generated by Django 3.0.7 on 2020-09-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskaction',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
