# Generated by Django 3.0.7 on 2020-09-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200921_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskaction',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
